---
title: "R ggvis for Library Data"
author: "Tim Dennis"
date: "April 25, 2015"
output: html_document
---

Creating interactive web graphics often requires classic challenges associated with **extract, load and transform** operations. Data needs to be acquired, cleaned, transformed and then sent to a web app for rendering. Each of these activities and steps can require different set of technical skills or alternately significant investment in a proprietary tool.  This leads to a barrier for an analyst or librarian to effectively explore data and create interactive graphics in a flexible, iterative way in single language. This chapter will cover how a new **R** package, **ggvis**, lets analysts build both beautiful static and interactive graphics for exploratory data analysis.  

In this chapter we explore using **ggvis** to build interactive web graphics of library data, including electronic resource usage, head count and ILS data. Because **ggvis** is based off the *grammar of graphis* and is part of a suite of R tools enabling a consistent vocabulary for managing and transforming data, the reader will gain confidence and a context for for both working with and telling stories with library data. 

We start the chapter by ensuring readers have all the tools necessary to follow along. To speed up getting up to speed on the computing, I'll provide a *VM* that will include all the tools, data and code samples needed to follow along. Once the computing is covered, we will introduce how **ggvis** utilizes the *grammar of graphics* to break graphs into composable components made up of data, a coordinate system, a mark type and properities, such as, fill color. This modularity allows us to easily alter these graphical components to make thousands of different plot types.  With a basic grasp of the *grammar of graphics* under our belts, we will start to use **ggvis** to build simple static graphs in R-Studio using library datasets the author will provide.  We will demonstrate how these graphics are rendered in html in our R-Studio graphics viewer. We will also introduce other important features the **ggvis** packages provides. For example, to improve the readability of our code, **ggvis** implements the **maggrittr** pipeline package that enables us to string together complex data operations in pipelines. We will also show how **ggvis** employs features from the **dplyr** package to prepare and transform the data for graphing. **flesh out last sentence** 

After covering the basics or graphing in **ggvis**, we will introduce intractivity to our plots.  Starting simply, we will xx to view single variable distribution graphs like histogram and density plot, adding various ggvis input types like sliders or select buttons.  The author will then introduce how to create interactive scatterplots or line graphs with xx. Finally, we will introduce and embed our ggvis plots in Rmarkdown. We will also cover, breifly how to embed and publish out ggvis plots in a shiny app. 
Finally, we discuss the current limitations of ggvis in that its in heavy development and no intended for production yet.  Also, adding multiplot layers is not yet in the feature set of ggvis.  However, with this in mind, ggvis opens the door for a librarian with knowledge of R to create interactive graphics without knowing the intricacies of a javascript framework and to do it while just speaking R. Furthermore, ggvis adoption of both a grammar of graphics and ability to compose multiple pipelines makes it flexible and powerful tool.  